- 👋 Hi, I’m @BrinzhI
- 👀 I’m interested in ...
- 🌱 I’m currently learning ...
- 💞️ I’m looking to collaborate on ...
- 📫 How to reach me ...

<!---
BrinzhI/BrinzhI is a ✨ special ✨ repository because its `README.md` (this file) appears on your GitHub profile.
You can click the Preview link to take a look at your changes.
--->
Hi I'm Filipino but nice kid and I don't know how to log in  in pojavlauncher so keep studying so login right now
